"""add_message_deleted_at

Revision ID: 17c9f3d4b966
Revises: b90b93f3412b
Create Date: 2026-04-25 03:33:07.049417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c9f3d4b966'
down_revision: Union[str, None] = 'b90b93f3412b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_at')
    # ### end Alembic commands ###
