"""add_room_member_left_at

Revision ID: 67eec8747489
Revises: 17c9f3d4b966
Create Date: 2026-04-25 03:33:43.274252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67eec8747489'
down_revision: Union[str, None] = '17c9f3d4b966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('left_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_members', 'left_at')
    # ### end Alembic commands ###
